#! /bin/sh

sxhkd &

#bspc monitor -d Música Trabalho Discord Firefox cinco seis sete oito nove dez
bspc monitor -d  いち に さん よん ご ろく しち はち きゅう ぬる
#bspc monitor -d  一  二  三  四  五  六  七  八  九 十

feh --randomize --bg-scale --no-fehbg ~/.config/cool\ bg/
#feh --bg-scale ~/Downloads/81821752_p0.jpeg

~/.config/polybar/launch.sh
uncluter &

picom --config ~/.config/picom/picom.conf -b &


#-------wacom bind
#xsetwacom --set 13 Button 2 2
#xsetwacom --set 13 Button 3 "key e"

#-------config

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding 	45
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle	true
bspc config gapless_monocle      true
bspc config normal_border_color '#282828'
bspc config focused_border_color '#f28833'
bspc config focus_follows_pointer true

#------rule
bspc rule -a polybar layer=normal
bspc rule -a PureRef state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=floating
bspc rule -a mpv layer=below focus=off state=fullscreen
bspc rule -a Firefox desktop=^4
bspc rule -a krita desktop=^2
bspc rule -a vlc desktop=^1
bspc rule -a discord desktop=^3
bspc rule -a typora state=gapless_monocle
xinput --set-prop "SIGMACHIP Usb Mouse" "libinput Accel Speed" -1
